# Generated by Django 3.1.7 on 2021-03-31 20:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='source_published',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
